### ISSUE TITLE
Handle creation of elements with mixed-content from csv

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#15]
Related to #2.

For some elements, like notes or abstracts, it would be useful to include mixed-content (text nodes and descendant elements) in the generated TEI.

Current plan on this is to implement 'placeHolders' and 'antecedents' columns in the csv.

So, for example, the following columns would specify nested elements in an abstract:

abstract.en | placeHolders.abstract.en | antecedents.element.abstract.en | antecedents.text.abstract.en | antecedents.uri.abstract.en

In this example, the abstract could contain text with place-holder characters: "Edessa is a city to the west of $, in modern day %. ^ taught at * there". The placeHolders.abstract.en would contain a pipe-separated sequence of characters corresponding to those used in the abstract cell: "$|%|^|*". 

The antecedents columns would then contain the data with which to replace the place holders. In this case, that could look like:

- antecedents.element.abstract.en:  'placeName|placeName|persName|placeName" (note that the element types do not have to be the same)
- antecedents.text.abstract.en: 'Nisibis|Turkey|Ephrem|a school' (potentially you could use a placeHolder here to have recursively nested descendants. This may be unnecessarily complex)
- antecdents.uri.abstract.en: 'http://syriaca.org/place/9999|http://syriaca.org/place/9998|http://syriaca.org/person/9998|http://syriaca.org/place/9997'

The transform would parse these columns to create the following:

```
<desc type="abstract" xml:id="abstract555555-1" resp="http://syriaca.org">Edessa is a city to the west of <placeName ref="http://syriaca.org/place/9999">Nisibis</placeName>, in modern day <placeName ref="http://syriaca.org/place/9998">Turkey</placeName>. <persName ref="http://syriaca.org/person/9998">Ephrem</persName> taught at <placeName ref="http://syriaca.org/place/9997">a school</placeName> there.</desc>

**Comment by wlpotter** [comment]
@dlschwartz we decided this was not worth the effort, is that correct?

**Comment by dlschwartz** [comment]
Correct, thanks.
