### ISSUE TITLE
Allow sources on headwords

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#19]
I believe we allow sources to be used on headwords? There are many cases of this in the persons data, but it was not the case for the places data.

The example for places in [The TEI Encoding Manual for TSG](https://github.com/srophe/srophe-app-data/wiki/TEI-Encoding-Manual-for-The-Syriac-Gazetteer#srophetagssyriaca-headword) under `@srophe:tags="#syriaca-headword"` does have this as a sourced headword.

Need to update how sourced headwords are handled.

**Comment by wlpotter** [comment]
This may also result in merging the functions for headwords and general entity names into a single function with a boolean flag for including the headword tag or not. And of course an enumeration off-set when running on 'generic' entity names (which will be passed the number of headwords)

**Comment by dlschwartz** [comment]
@wlpotter Regardless of headword, tei:placeName in the Gazetteer requires either a `@source` or a `@resp`. We will want the same for tei:persName in SBD.

See https://github.com/srophe/srophe-eXist-app/blob/master/documentation/schemas/syriacaPlaces.odd#L291:#L302

**Comment by wlpotter** [comment]
@dlschwartz thanks for this. I had the script adding either a `@source` or `@resp` for the non-headword names, but for some reason I had only allowed `@resp` for headwords. I will update the script to choose on both headword and non-headword names.

**Comment by wlpotter** [comment]
This is fixed with https://github.com/wlpotter/csv-to-srophe/commit/2835f6a26af9d8151a623e7d8e1b314bb99114a9
