### ISSUE TITLE
Ensure dates are ISO-compliant

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#26]
Issue raised in #24 

> The dates are not compliant. I think the solution here is to make sure we put a compliant date format into the spreadsheet (yyyy-mm-dd). I should be able to write a regex to validate the data in columns U, V, and W unless you'd like to do that. Come to think of it, I'm sure there is a regex out there we can search for and steal.

If we enforce in the spreadsheet, the script should simply raise an error if it encounters a non-ISO date format in the attribute columns.

**Comment by dlschwartz** [comment]
I've updated the dates in the google sheet. https://docs.google.com/spreadsheets/d/1SZpHjRSl2wAfa_FEpsGxYq8MMUNlBTNljitZiXJOv8s/edit#gid=336228761

**Comment by wlpotter** [comment]
I've added data validation in the Google sheet.

I've also added date formats to the list of error handling needs in #27.
