### ISSUE TITLE
Change `entryFree/@type="skos:concept"` to the full URI

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#42]
Current: "skos:concept"

Update to: "http://www.w3.org/2004/02/skos/core#Concept"

@dlschwartz FYI since every keyword is treated as a skos:Concept, we don't mark it anywhere in the spreadsheet; the script just adds it automatically as the `entryFree/@type`. Unless there might be a reason down the line to have keywords that aren't skos:Concept, I think it's fine not to mark in the spreadsheet?

FWIW, if a keyword isn't a skos:Concept I'm not sure we'd want an XML record for it anyway?

**Comment by dlschwartz** [comment]
@wlpotter I agree. At least as far as I can see, everything in the taxonomy will by definition be a skos:concept (or some equivalent in another vocabulary should our ontology work take us there).
