### ISSUE TITLE
Abstracts do not need xml:id attributes

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#51]
The abstracts in persons and places no longer need xml:id attributes

**Comment by wlpotter** [comment]
I want to raise this with the editors on how to handle multiple, project-specific abstracts as this may affect how we resolve this issue?

**Comment by wlpotter** [comment]
@dlschwartz I know we are moving away from xml:id attributes on abstracts (descs or notes, depending on the entity). However, I remember in our discussions regarding John of Ephesus that we might have a project-specific view of the data that pulls in only the relevant elements. The question here is how we will mark the J of E-specific abstract? We may not have decided yet, but this will be relevant for how the transform generates the abstract elements, both for J of E and more generally

**Comment by dlschwartz** [comment]
Yes, let's discuss. I'm not sure @xml:id is the most helpful solution to multiple abstracts.

**Comment by wlpotter** [comment]
This should be fixed; #65 is for the change to use `@corresp` attributes to associate abstracts with their series
