### ISSUE TITLE
Person elements should be reordered to appear in the order specified by the updated schema

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#57]
Note: need to first verify the correct order of elements

**Comment by wlpotter** [comment]
@dlschwartz this is probably something I should be able to figure out from the schema, but I still have a bit of trouble parsing it...If memory serves we specified a required element order for the children of persons (and places??). Where might I find documentation of the correct order, as I believe I am getting a few validation errors on the transform outputs because the elements are out of order?

**Comment by dlschwartz** [comment]
This is from the [syriacaPersons.odd](https://github.com/srophe/syriaca/blob/2023_SchemaWork/documentation/schemas/syriacaPersons.odd#L560) which constrains the order to the one below:

```
         <content>
            <sequence minOccurs="1" maxOccurs="1" preserveOrder="true">
              <elementRef key="persName" minOccurs="1" maxOccurs="unbounded"/>
              <elementRef key="idno" minOccurs="1" maxOccurs="unbounded"/>
              <elementRef key="note" minOccurs="0" maxOccurs="unbounded"/> <!-- This needs to be changed to minOccurs="1". Every record needs an abstract. -->
              <elementRef key="floruit" minOccurs="0" maxOccurs="unbounded"/>
              <elementRef key="birth" minOccurs="0" maxOccurs="unbounded"/>
              <elementRef key="death" minOccurs="0" maxOccurs="unbounded"/>
              <elementRef key="gender" minOccurs="0" maxOccurs="unbounded"/>
              <elementRef key="state" minOccurs="0" maxOccurs="unbounded"/>
              <elementRef key="trait" minOccurs="0" maxOccurs="unbounded"/>
              <elementRef key="event" minOccurs="0" maxOccurs="unbounded"/>
              <elementRef key="bibl" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
          </content>
```

**Comment by wlpotter** [comment]
Fixed. Note to self that `event` is not yet a supported element (and shouldn't be needed for J of E
