### ISSUE TITLE
Floruit in persons throwing validation error with `@notBefore` and `@notAfter` attributes

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#58]
This may be related to #57 (i.e., the error may be because the element is not in order), but currently am receiving the following validation error on this code:

`<floruit source="#bib2538-2" notBefore="0500" notAfter="0550">early 6th century</floruit>`

>found attribute "source", but not attributes allowed here

(similar errors for the other attributes). Raise as a question

**Comment by wlpotter** [comment]
@dlschwartz I'm getting a validation error on the above floruit element and might just be forgetting what change we made. I think there might also be element ordering errors (cf. #57 ), but this one seemed separate from that?

For reference, it is [this line of code](https://github.com/wlpotter/csv-to-srophe/blob/main/out/persons/2021-11-17/2538.xml#L114)

**Comment by dlschwartz** [comment]
Try: `<floruit><date notBefore="0500" notAfter="0550" source="#bib2538-2">early 6th century</date></floruit>`

**Comment by wlpotter** [comment]
Fixed
