### ISSUE TITLE
Build taxonomy module(s)

### ISSUE THREAD

**Issue by wlpotter** [wlpotter/csv-to-srophe#6]

**Comment by wlpotter** [comment]
This is a good example file for developing this module.

https://github.com/srophe/srophe-app-data/blob/master/data/subjects/tei/afterlife.xml

Should just use the main csv2srophe with a few extensions and can make a subjects-template.xml file for it.

Get the CSV data to see how it needs to adapt.

**Comment by wlpotter** [comment]
@dlschwartz I am optimistic that this module should come online much more quickly than the others as we already handle most of the data types in the transform, so it's just a matter of altering the output elements and record order.

I do have a few questions and recommendations for the spreadsheet [here](https://docs.google.com/spreadsheets/d/14jU8K-hjFH193zsqXzrdYPYfx2HFqttX0TPScdsbukA/edit#gid=959652535). No rush on these; let me know what you think when you get a chance.

1. Column B (subjectType): where should this appear in the XML? Example: https://syriaca.org/keyword/clerical-relationships/tei is "category" in row 164 of the spreadsheet, but that does not appear anywhere in the XML.
2. Column C (source): does this affect any of the output? All entries appear to have the tei:respStmt for coming from CBSC. Is this column just for reference?
3. Column D (currently in use): should this be output? What is the function of this column?
4. Column E (Categories): this appears to be the `//entryFree/@subtype` value, is that right?
5. Column G (relType): this appears to be the `//entryFree/idno[@type="SPEAR]/@ana` value (for SPEAR idno elements), is that right?
    - May need to change the label to something like: ana.idno.SPEAR (cf. question 6, below).
6. Columns J-K (non-URI idnos): Currently, the script assumes that all idno columns in the spreadsheet should output as `@type="URI"`. It looks like this should change. 
    - I wonder if the idno columns should instead have the form `idno.attrVal`, where 'attrVal' is the exact, case-sensitive name of the `@type` value on the idno. The most common would be `idno.URI` but we could here have `idno.SPEAR`. For the lang code, as it is untyped, we would leave it as `idno`.
    - Another option would be to rename these two columns to specify that they are ISO lang codes and SPEAR identifiers. This would be simpler in the sense of not disturbing our previous spreadsheet formats, but if there might be other cases down-the-line where we'd want non-URI idno elements, I'd recommend the first option (`idno.attrVal`).
 7. Columns AF-CI (skos:broadMatch relations): We can rename these to relation1.skosBroadMatch...relationN.skosBroadMatch. There are two options here:
     - We can collapse these down to the minimum number of columns needed based on the row that has the most non-blank cells from AF-CI (the winner is Baptism, with 6 filled-in skos:broadMatch relations). We could implement data validation on these columns so you would get a drop-down of valid keyword URIs.
     - We can change the column names but leave the amount as-is. We can also leave the second and third rows as guides if that is useful for people entering data. The script skips over empty columns, so the main reason to collapse these columns would be to avoid an unwieldy number of columns.
8. Column CJ (revisit): I'm assuming this is not needed in the output, but could we use it as part of the `newOrAppend` flag? We could expand that flag to include `ignore` as a value which would tell the script to skip columns if they're not ready for processing. It seems like getting #3 fixed is a priority here as a lot of what's in the taxonomy spreadsheet is already in XML. This might also be a good time to think about #4.

**Comment by dlschwartz** [comment]
@wlpotter well this is a little embarrassing, it's way worse than I thought.  

1. Column B must be a holdover from a earlier stage of data collection and organization. Everything there is replicated in either column CI or CG. We can delete that column.
2. Column C was mainly about keeping track of CBSC keywords. We're not currently transforming that. However, at one point in discussing things with Sergey, he was concerned with the expansion of the keywords. He didn't really want to engage with all of the new ones. Or at least he wanted a way to work with a subset of the growing list of keywords. We could use this column to designate a subset of CBSC keywords. That said, we wouldn't necessarily need that in the TEI record. That subset could simply live in Zotero. This might need some discussion.
3. Column D contains what was at one time the CBSC keyword (I'm not sure what changes CBSC may have made recently). This column should be the most up-to-date crosswalk we have. I was mistaken the other day when I indicated the "OLD subject headings" tab. This is the most current crosswalk. And no, this is not currently being picked up for the transform.
4. That is correct. What we do with this column will probably change as we work on developing the ontology. It is currently used in Srophe for browsing by these categories. The feature is not working right now but it should display a list of these 42 categories and when the user clicks on one of them it should display all of the keywords in that category.
5. The only use of this information is in SPEAR. I have an xslt that transforms the taxonomy into an index. I use the data here to validate that some relationships get a `@mutual` attribute while others get `@active`/`@passive`. The label can definitely change. By the way, I've been meaning to change "reciprocal" to "directed" for ages and I've done that in the spreadsheet.
6. Yes, these need work. I like your second suggestion with a bit of modification. 
    - I would like multiple columns that will output `<idno @type="URI">`. I'm currently looking at LOC and DNB but we might want to include others. Whatever column heading you want to use for that purpose will be great. 
    - We should definitely rename the ISO column as you suggest. 
    - Column K is a bit of a relic. There was a time when SPEAR was using namespaced relationship types but we've switched over to Syriaca URIs instead. Column K still serves a purpose, however. It offers a crosswalk between Syriaca URIs and equivalent snap relationships. Whatever column heading works for that purpose would be fine. 
    - I think we also need an additional column here. We have relationships that are more precise than snap relationships. For example, we get fairly fine-grained regarding clerical relationships: bishop-over-clergy, fellow-monastic, etc.. In a LOD environment, we will want to serve these up our more specific relationship to snap as their rather generic "professional relationship." I haven't worked out how to render this in TEI but I should probably do that and create a column for that purpose. 
7. Let's go with your first suggestion here. The dropdown would be fantastic and would accomplish what my proliferation of columns is doing but in a much better way.
8. This is an interesting idea. We might need to think a bit about how this will work. We do want to have this as a way to create new keywords. However, we will also want to use this to rerun the transform for all records. Here I'm thinking on what I want to do with open refine in terms of enhancing the records with links to other datasets (LOC, etc., this work is far from done). In this case we might want to simply use separate tabs with identical headings (notice that we currently have "Subjects" and "To Transform"). But maybe not. Maybe it's easier to have one sheet. Let's chat about this one.

Hopefully this is enough for you to get started on this Will. Let me know if you have any questions. Thanks!

**Comment by wlpotter** [comment]
1. Sounds good, I will delete column B.
2. I will make an issue to discuss this.
3. This is helpful to know, and I've noted for myself that this is the most recent crosswalk. I'll leave it out of the transform for now.
4. Sounds good.
5. See next
6. Let's keep `idno` as the column header for the LOC and DNB URIs (and any others that would be `<idno type="URI">`). For the language code, something like `isoLangCode` or `iso639` would be fine. 
    - For SNAP relations, I've opened a separate issue, #35 and assigned it to you. Let me know there how you'd want the TEI to look and add a column to the sheet for the more-specific Syriaca URI. The TEI output will determine how we name and handle these columns.
7. Sounds good; I'll add the data validation for the drop-down to the sheet and collapse the columns down.
8. Sounds good, we can discuss. I'll put the results of that discussion in #4

**Comment by wlpotter** [comment]
I believe everything here is either addressed or moved to separate issues. A first draft of the transform is working, and further development discussion can take place in #39
